language: python

python:
  - "3.7"

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=pbtools setup.py test
  - make test-c
  - make -C examples/c/hello_world
  - make -C examples/c/address_book
  - make -C examples/c/oneof
  - make -C examples/python/hello_world
  - make -C examples/python/address_book
  - make -C examples/python/oneof
  - make -C benchmark ITERATIONS=1

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash) -X coveragepy
